name: test endpoints
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - uses: actions/setup-python@v2
        with:
            python-version: '3.8'
      - run: npm install
      - run: pip install -r requirements.txt
      - run: npm test
